alter table if exists poll drop constraint if exists FKays4ctjjq00nj9fcb0spy1juc;
alter table if exists vote drop constraint if exists FKe0wq53r6cxdsssvfrymxr4pe6;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists app_user cascade;
drop table if exists poll cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
drop sequence if exists app_user_seq;
drop sequence if exists poll_seq;
drop sequence if exists vote_option_seq;
drop sequence if exists vote_seq;
alter table if exists poll drop constraint if exists FKays4ctjjq00nj9fcb0spy1juc;
alter table if exists vote drop constraint if exists FKe0wq53r6cxdsssvfrymxr4pe6;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists app_user cascade;
drop table if exists poll cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
drop sequence if exists app_user_seq;
drop sequence if exists poll_seq;
drop sequence if exists vote_option_seq;
drop sequence if exists vote_seq;
alter table if exists poll drop constraint if exists FKays4ctjjq00nj9fcb0spy1juc;
alter table if exists vote drop constraint if exists FKe0wq53r6cxdsssvfrymxr4pe6;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists app_user cascade;
drop table if exists poll cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
drop sequence if exists app_user_seq;
drop sequence if exists poll_seq;
drop sequence if exists vote_option_seq;
drop sequence if exists vote_seq;
alter table if exists poll drop constraint if exists FKays4ctjjq00nj9fcb0spy1juc;
alter table if exists vote drop constraint if exists FKe0wq53r6cxdsssvfrymxr4pe6;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists app_user cascade;
drop table if exists poll cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
drop sequence if exists app_user_seq;
drop sequence if exists poll_seq;
drop sequence if exists vote_option_seq;
drop sequence if exists vote_seq;
alter table if exists poll drop constraint if exists FKays4ctjjq00nj9fcb0spy1juc;
alter table if exists vote drop constraint if exists FKe0wq53r6cxdsssvfrymxr4pe6;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists app_user cascade;
drop table if exists poll cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
drop sequence if exists app_user_seq;
drop sequence if exists poll_seq;
drop sequence if exists vote_option_seq;
drop sequence if exists vote_seq;
alter table if exists poll drop constraint if exists FKays4ctjjq00nj9fcb0spy1juc;
alter table if exists vote drop constraint if exists FKe0wq53r6cxdsssvfrymxr4pe6;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists app_user cascade;
drop table if exists poll cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
drop sequence if exists app_user_seq;
drop sequence if exists poll_seq;
drop sequence if exists vote_option_seq;
drop sequence if exists vote_seq;
alter table if exists poll drop constraint if exists FKays4ctjjq00nj9fcb0spy1juc;
alter table if exists vote drop constraint if exists FKe0wq53r6cxdsssvfrymxr4pe6;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists app_user cascade;
drop table if exists poll cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
drop sequence if exists app_user_seq;
drop sequence if exists poll_seq;
drop sequence if exists vote_option_seq;
drop sequence if exists vote_seq;
alter table if exists poll drop constraint if exists FKays4ctjjq00nj9fcb0spy1juc;
alter table if exists vote drop constraint if exists FKe0wq53r6cxdsssvfrymxr4pe6;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists app_user cascade;
drop table if exists poll cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
drop sequence if exists app_user_seq;
drop sequence if exists poll_seq;
drop sequence if exists vote_option_seq;
drop sequence if exists vote_seq;
alter table if exists poll drop constraint if exists FKays4ctjjq00nj9fcb0spy1juc;
alter table if exists vote drop constraint if exists FKe0wq53r6cxdsssvfrymxr4pe6;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists app_user cascade;
drop table if exists poll cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
drop sequence if exists app_user_seq;
drop sequence if exists poll_seq;
drop sequence if exists vote_option_seq;
drop sequence if exists vote_seq;
alter table if exists poll drop constraint if exists FKays4ctjjq00nj9fcb0spy1juc;
alter table if exists vote drop constraint if exists FKe0wq53r6cxdsssvfrymxr4pe6;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists app_user cascade;
drop table if exists poll cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
drop sequence if exists app_user_seq;
drop sequence if exists poll_seq;
drop sequence if exists vote_option_seq;
drop sequence if exists vote_seq;
